language: node_js
node_js:
- '7.5.0'
sudo: required
before_install:
  - npm install -g node-gyp
  - npm install -g protractor
  - npm install -g newman
before_script:
   - chmod +x ./deploy.sh
script: ./deploy.sh

addons:
  sauce_connect:
    username: "nedved"
    access_key: "6d31c524-7dc8-40f3-84da-c92c9ffc1514"
