language: 
  node_js
node_js:
  - '7.5.0'
env:
  - CXX=g++-4.8
sudo: 
  required
install: 
  - npm install -g webdriverio
  - npm install -g newman
  - npm install -g wdio-jasmine-framework
before_script:
  - chmod +x ./deploy.sh
script:
  ./deploy.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  sauce_connect:
    username: "jkentreynes"
    access_key: "84d0d96c-6b36-41e2-a0f3-9da1e6772731"
